import type { AssetEntry } from './price-cache.types';

/**
 * Curated list of ~230 actively-traded US equities used as a fallback when
 * ALPACA_API_KEY / ALPACA_API_SECRET are not set (local dev, CI without creds).
 * Mirrors the shape returned by Alpaca's GET /v2/assets endpoint.
 */
export const MOCK_ASSETS: AssetEntry[] = [
  // Technology — NASDAQ
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc. Class A',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GOOG',
    name: 'Alphabet Inc. Class C',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CSCO',
    name: 'Cisco Systems Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'INTC',
    name: 'Intel Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'QCOM',
    name: 'QUALCOMM Incorporated',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TXN',
    name: 'Texas Instruments Incorporated',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MU',
    name: 'Micron Technology Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AMAT',
    name: 'Applied Materials Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LRCX',
    name: 'Lam Research Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'KLAC',
    name: 'KLA Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SNPS',
    name: 'Synopsys Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CDNS',
    name: 'Cadence Design Systems Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NOW',
    name: 'ServiceNow Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'INTU',
    name: 'Intuit Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PANW',
    name: 'Palo Alto Networks Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'FTNT',
    name: 'Fortinet Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DDOG',
    name: 'Datadog Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TEAM',
    name: 'Atlassian Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ZM',
    name: 'Zoom Video Communications Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DOCU',
    name: 'DocuSign Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'OKTA',
    name: 'Okta Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NET',
    name: 'Cloudflare Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MNDY',
    name: 'monday.com Ltd.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'S',
    name: 'SentinelOne Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'IBM',
    name: 'International Business Machines',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ACN',
    name: 'Accenture plc',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'MSCI', name: 'MSCI Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },

  // Consumer tech / platforms
  {
    symbol: 'UBER',
    name: 'Uber Technologies Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LYFT',
    name: 'Lyft Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ABNB',
    name: 'Airbnb Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DASH',
    name: 'DoorDash Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'HOOD',
    name: 'Robinhood Markets Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SOFI',
    name: 'SoFi Technologies Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AFRM',
    name: 'Affirm Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'UPST',
    name: 'Upstart Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'SQ', name: 'Block Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'PYPL',
    name: 'PayPal Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ETSY',
    name: 'Etsy Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EBAY',
    name: 'eBay Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'SNAP', name: 'Snap Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'PINS',
    name: 'Pinterest Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'RBLX',
    name: 'Roblox Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TTWO',
    name: 'Take-Two Interactive Software',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EA',
    name: 'Electronic Arts Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MTCH',
    name: 'Match Group Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DKNG',
    name: 'DraftKings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Healthcare
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'UNH',
    name: 'UnitedHealth Group Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LLY',
    name: 'Eli Lilly and Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MRK',
    name: 'Merck & Co. Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BMY',
    name: 'Bristol-Myers Squibb Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AMGN',
    name: 'Amgen Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GILD',
    name: 'Gilead Sciences Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'REGN',
    name: 'Regeneron Pharmaceuticals Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BIIB',
    name: 'Biogen Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'VRTX',
    name: 'Vertex Pharmaceuticals Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MRNA',
    name: 'Moderna Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BNTX',
    name: 'BioNTech SE',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'CVS',
    name: 'CVS Health Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CI',
    name: 'The Cigna Group',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'HUM', name: 'Humana Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'ELV',
    name: 'Elevance Health Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MCK',
    name: 'McKesson Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'IDXX',
    name: 'IDEXX Laboratories Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'ISRG',
    name: 'Intuitive Surgical Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TMO',
    name: 'Thermo Fisher Scientific Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DHR',
    name: 'Danaher Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SYK',
    name: 'Stryker Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BSX',
    name: 'Boston Scientific Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MDT',
    name: 'Medtronic plc',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EW',
    name: 'Edwards Lifesciences Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BDX',
    name: 'Becton Dickinson and Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DXCM',
    name: 'DexCom Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ALGN',
    name: 'Align Technology Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'IQV',
    name: 'IQVIA Holdings Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Financials
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WFC',
    name: 'Wells Fargo & Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GS',
    name: 'The Goldman Sachs Group Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MS',
    name: 'Morgan Stanley',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BLK',
    name: 'BlackRock Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SCHW',
    name: 'The Charles Schwab Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AXP',
    name: 'American Express Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'COF',
    name: 'Capital One Financial Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'USB',
    name: 'U.S. Bancorp',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PNC',
    name: 'The PNC Financial Services Group',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TFC',
    name: 'Truist Financial Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'C',
    name: 'Citigroup Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BK',
    name: 'The Bank of New York Mellon',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'STT',
    name: 'State Street Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'FITB',
    name: 'Fifth Third Bancorp',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'KEY', name: 'KeyCorp', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'RF',
    name: 'Regions Financial Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CFG',
    name: 'Citizens Financial Group Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ALLY',
    name: 'Ally Financial Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'MSCI', name: 'MSCI Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },

  // Energy
  {
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CVX',
    name: 'Chevron Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'COP',
    name: 'ConocoPhillips',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SLB',
    name: 'Schlumberger Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EOG',
    name: 'EOG Resources Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MPC',
    name: 'Marathon Petroleum Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'PSX', name: 'Phillips 66', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'VLO',
    name: 'Valero Energy Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'OXY',
    name: 'Occidental Petroleum Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DVN',
    name: 'Devon Energy Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'HES',
    name: 'Hess Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'KMI',
    name: 'Kinder Morgan Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WMB',
    name: 'Williams Companies Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'OKE', name: 'ONEOK Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'EPD',
    name: 'Enterprise Products Partners L.P.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ET',
    name: 'Energy Transfer LP',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Consumer Discretionary
  {
    symbol: 'HD',
    name: 'The Home Depot Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LOW',
    name: "Lowe's Companies Inc.",
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TGT',
    name: 'Target Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MCD',
    name: "McDonald's Corporation",
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SBUX',
    name: 'Starbucks Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'NKE', name: 'NIKE Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'LULU',
    name: 'lululemon athletica inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ROST',
    name: 'Ross Stores Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TJX',
    name: 'The TJX Companies Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CMG',
    name: 'Chipotle Mexican Grill Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'YUM',
    name: 'Yum! Brands Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'QSR',
    name: 'Restaurant Brands International',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DRI',
    name: 'Darden Restaurants Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'W', name: 'Wayfair Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'BKNG',
    name: 'Booking Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EXPE',
    name: 'Expedia Group Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MAR',
    name: 'Marriott International Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'HLT',
    name: 'Hilton Worldwide Holdings Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CCL',
    name: 'Carnival Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'RCL',
    name: 'Royal Caribbean Group',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NCLH',
    name: 'Norwegian Cruise Line Holdings',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DAL',
    name: 'Delta Air Lines Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'UAL',
    name: 'United Airlines Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AAL',
    name: 'American Airlines Group Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LUV',
    name: 'Southwest Airlines Co.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Consumer Staples
  {
    symbol: 'WMT',
    name: 'Walmart Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'COST',
    name: 'Costco Wholesale Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PEP',
    name: 'PepsiCo Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PG',
    name: 'The Procter & Gamble Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CL',
    name: 'Colgate-Palmolive Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'KMB',
    name: 'Kimberly-Clark Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MDLZ',
    name: 'Mondelez International Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GIS',
    name: 'General Mills Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'K', name: 'Kellanova', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'HSY',
    name: 'The Hershey Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TSN',
    name: 'Tyson Foods Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'KHC',
    name: 'The Kraft Heinz Company',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'STZ',
    name: 'Constellation Brands Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MO',
    name: 'Altria Group Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PM',
    name: 'Philip Morris International Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Industrials
  {
    symbol: 'BA',
    name: 'The Boeing Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CAT',
    name: 'Caterpillar Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'HON',
    name: 'Honeywell International Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'MMM', name: '3M Company', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  { symbol: 'GE', name: 'GE Aerospace', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'UPS',
    name: 'United Parcel Service Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'FDX',
    name: 'FedEx Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LMT',
    name: 'Lockheed Martin Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'RTX',
    name: 'RTX Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NOC',
    name: 'Northrop Grumman Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GD',
    name: 'General Dynamics Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DE',
    name: 'Deere & Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EMR',
    name: 'Emerson Electric Co.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ETN',
    name: 'Eaton Corporation plc',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PH',
    name: 'Parker-Hannifin Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ROK',
    name: 'Rockwell Automation Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ROP',
    name: 'Roper Technologies Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'AME', name: 'AMETEK Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'TDG',
    name: 'TransDigm Group Incorporated',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'IR',
    name: 'Ingersoll Rand Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ODFL',
    name: 'Old Dominion Freight Line Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'JBHT',
    name: 'J.B. Hunt Transport Services',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'XPO', name: 'XPO Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'CARR',
    name: 'Carrier Global Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'OTIS',
    name: 'Otis Worldwide Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Communication Services
  {
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CMCSA',
    name: 'Comcast Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'T', name: 'AT&T Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'TMUS',
    name: 'T-Mobile US Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CHTR',
    name: 'Charter Communications Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PARA',
    name: 'Paramount Global',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WBD',
    name: 'Warner Bros. Discovery Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'FOXA',
    name: 'Fox Corporation Class A',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SIRI',
    name: 'Sirius XM Holdings Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SPOT',
    name: 'Spotify Technology S.A.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Utilities
  {
    symbol: 'NEE',
    name: 'NextEra Energy Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'DUK',
    name: 'Duke Energy Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SO',
    name: 'Southern Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AEP',
    name: 'American Electric Power Company',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'D',
    name: 'Dominion Energy Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EXC',
    name: 'Exelon Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'XEL',
    name: 'Xcel Energy Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'SRE', name: 'Sempra', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'PCG',
    name: 'PG&E Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AWK',
    name: 'American Water Works Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CEG',
    name: 'Constellation Energy Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'VST',
    name: 'Vistra Corp.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Real Estate
  {
    symbol: 'AMT',
    name: 'American Tower Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PLD',
    name: 'Prologis Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CCI',
    name: 'Crown Castle Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EQIX',
    name: 'Equinix Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'O',
    name: 'Realty Income Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SPG',
    name: 'Simon Property Group Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WELL',
    name: 'Welltower Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'AVB',
    name: 'AvalonBay Communities Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'EQR',
    name: 'Equity Residential',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PSA',
    name: 'Public Storage',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'VTR', name: 'Ventas Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'ARE',
    name: 'Alexandria Real Estate Equities',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MAA',
    name: 'Mid-America Apartment Communities',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Materials
  { symbol: 'LIN', name: 'Linde plc', exchange: 'NASDAQ', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'SHW',
    name: 'The Sherwin-Williams Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'FCX',
    name: 'Freeport-McMoRan Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NEM',
    name: 'Newmont Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'APD',
    name: 'Air Products and Chemicals Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'ECL', name: 'Ecolab Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'DD',
    name: 'DuPont de Nemours Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'PPG',
    name: 'PPG Industries Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NUE',
    name: 'Nucor Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'VMC',
    name: 'Vulcan Materials Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MLM',
    name: 'Martin Marietta Materials Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ALB',
    name: 'Albemarle Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'CF',
    name: 'CF Industries Holdings Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MOS',
    name: 'The Mosaic Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Automotive / EVs
  {
    symbol: 'F',
    name: 'Ford Motor Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GM',
    name: 'General Motors Company',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'RIVN',
    name: 'Rivian Automotive Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'LCID',
    name: 'Lucid Group Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  { symbol: 'NIO', name: 'NIO Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  { symbol: 'XPEV', name: 'XPeng Inc.', exchange: 'NYSE', tradable: true, assetClass: 'us_equity' },
  {
    symbol: 'LI',
    name: 'Li Auto Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Semiconductors (additional)
  {
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'MRVL',
    name: 'Marvell Technology Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'NXPI',
    name: 'NXP Semiconductors N.V.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ON',
    name: 'ON Semiconductor Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'STM',
    name: 'STMicroelectronics N.V.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WOLF',
    name: 'Wolfspeed Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'SMCI',
    name: 'Super Micro Computer Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ARM',
    name: 'Arm Holdings plc',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },

  // Cloud / SaaS (additional)
  {
    symbol: 'ZS',
    name: 'Zscaler Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'WDAY',
    name: 'Workday Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'TTD',
    name: 'The Trade Desk Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'APP',
    name: 'AppLovin Corporation',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'HUBS',
    name: 'HubSpot Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'BILL',
    name: 'BILL Holdings Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'ZI',
    name: 'ZoomInfo Technologies Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'U',
    name: 'Unity Software Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'us_equity',
  },
  {
    symbol: 'GTLB',
    name: 'GitLab Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_equity',
  },
];

export const MOCK_UK_ASSETS: AssetEntry[] = [
  // Banking & Finance
  {
    symbol: 'HSBA.L',
    name: 'HSBC Holdings plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BARC.L',
    name: 'Barclays plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'LLOY.L',
    name: 'Lloyds Banking Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'NWG.L',
    name: 'NatWest Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'STAN.L',
    name: 'Standard Chartered plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'AVIVA.L',
    name: 'Aviva plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'PRU.L',
    name: 'Prudential plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'LGEN.L',
    name: 'Legal & General Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'MNG.L', name: 'M&G plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },

  // Energy
  { symbol: 'BP.L', name: 'BP plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  { symbol: 'SHEL.L', name: 'Shell plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },

  // Mining & Materials
  {
    symbol: 'RIO.L',
    name: 'Rio Tinto plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'AAL.L',
    name: 'Anglo American plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BHP.L',
    name: 'BHP Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'GLEN.L',
    name: 'Glencore plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'ANTO.L',
    name: 'Antofagasta plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Pharmaceuticals & Healthcare
  {
    symbol: 'AZN.L',
    name: 'AstraZeneca plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'GSK.L', name: 'GSK plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  { symbol: 'HLN.L', name: 'Haleon plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'SHPG.L',
    name: 'Smith+Nephew plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Consumer Goods
  {
    symbol: 'ULVR.L',
    name: 'Unilever plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BATS.L',
    name: 'British American Tobacco plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'IMB.L',
    name: 'Imperial Brands plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'DGE.L', name: 'Diageo plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'ABF.L',
    name: 'Associated British Foods plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'TSCO.L', name: 'Tesco plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'SBRY.L',
    name: 'J Sainsbury plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'MKS.L',
    name: 'Marks and Spencer Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'JD.L',
    name: 'JD Sports Fashion plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'OCDO.L',
    name: 'Ocado Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Industrials & Aerospace
  {
    symbol: 'BA.L',
    name: 'BAE Systems plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'RR.L',
    name: 'Rolls-Royce Holdings plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'WEIR.L',
    name: 'Weir Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'IMI.L', name: 'IMI plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  { symbol: 'HLMA.L', name: 'Halma plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },

  // Telecoms & Technology
  {
    symbol: 'VOD.L',
    name: 'Vodafone Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BT.L',
    name: 'BT Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'SAGE.L',
    name: 'Sage Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Media & Entertainment
  { symbol: 'REL.L', name: 'RELX plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'PSON.L',
    name: 'Pearson plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'WPP.L', name: 'WPP plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },

  // Real Estate
  { symbol: 'SGRO.L', name: 'SEGRO plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'LAND.L',
    name: 'Land Securities Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BLND.L',
    name: 'British Land Company plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BKG.L',
    name: 'Berkeley Group Holdings plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'BDEV.L',
    name: 'Barratt Developments plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'PSN.L',
    name: 'Persimmon plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'TW.L',
    name: 'Taylor Wimpey plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Utilities
  {
    symbol: 'NG.L',
    name: 'National Grid plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'SSE.L', name: 'SSE plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  {
    symbol: 'CNA.L',
    name: 'Centrica plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'UU.L',
    name: 'United Utilities Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'SVT.L',
    name: 'Severn Trent plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Aviation & Travel
  {
    symbol: 'IAG.L',
    name: 'International Consolidated Airlines Group',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'EZJ.L',
    name: 'easyJet plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'WIZZ.L',
    name: 'Wizz Air Holdings plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'CPG.L',
    name: 'Compass Group plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  {
    symbol: 'WTB.L',
    name: 'Whitbread plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },

  // Professional Services
  {
    symbol: 'EXPN.L',
    name: 'Experian plc',
    exchange: 'LSE',
    tradable: true,
    assetClass: 'uk_equity',
  },
  { symbol: 'MNDI.L', name: 'Mondi plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
  { symbol: 'DCC.L', name: 'DCC plc', exchange: 'LSE', tradable: true, assetClass: 'uk_equity' },
];

export const MOCK_ETF_ASSETS: AssetEntry[] = [
  // Broad market
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust Series 1',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'DIA',
    name: 'SPDR Dow Jones Industrial Average ETF Trust',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  // Sector
  {
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLV',
    name: 'Health Care Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLI',
    name: 'Industrial Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLY',
    name: 'Consumer Discretionary Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLP',
    name: 'Consumer Staples Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLU',
    name: 'Utilities Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'XLRE',
    name: 'Real Estate Select Sector SPDR Fund',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  // Thematic / leveraged
  {
    symbol: 'ARKK',
    name: 'ARK Innovation ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'SOXL',
    name: 'Direxion Daily Semiconductor Bull 3x Shares',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'TQQQ',
    name: 'ProShares UltraPro QQQ',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'SQQQ',
    name: 'ProShares UltraPro Short QQQ',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_etf',
  },
  // Fixed income & commodities
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'HYG',
    name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  // International
  {
    symbol: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'EFA',
    name: 'iShares MSCI EAFE ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'FXI',
    name: 'iShares China Large-Cap ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
  {
    symbol: 'VEA',
    name: 'Vanguard FTSE Developed Markets ETF',
    exchange: 'NYSE ARCA',
    tradable: true,
    assetClass: 'us_etf',
  },
];

export const MOCK_GLOBAL_ASSETS: AssetEntry[] = [
  // Europe — Netherlands
  {
    symbol: 'ASML',
    name: 'ASML Holding N.V.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'PHIA',
    name: 'Koninklijke Philips N.V.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'ING',
    name: 'ING Groep N.V.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Europe — Germany
  { symbol: 'SAP', name: 'SAP SE', exchange: 'NYSE', tradable: true, assetClass: 'intl_equity' },
  {
    symbol: 'SIEGY',
    name: 'Siemens AG',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  { symbol: 'BAYRY', name: 'Bayer AG', exchange: 'OTC', tradable: true, assetClass: 'intl_equity' },
  // Europe — Switzerland
  {
    symbol: 'NESN',
    name: 'Nestlé S.A.',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'NVS',
    name: 'Novartis AG',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'ROG',
    name: 'Roche Holding AG',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Europe — Denmark
  {
    symbol: 'NVO',
    name: 'Novo Nordisk A/S',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Europe — France
  {
    symbol: 'MC',
    name: 'LVMH Moët Hennessy',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'TTE',
    name: 'TotalEnergies SE',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  { symbol: 'AIR', name: 'Airbus SE', exchange: 'OTC', tradable: true, assetClass: 'intl_equity' },
  // Europe — Spain
  {
    symbol: 'BBVA',
    name: 'Banco Bilbao Vizcaya Argentaria',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'SAN',
    name: 'Banco Santander S.A.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Europe — Sweden
  {
    symbol: 'ERIC',
    name: 'Ericsson',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — Taiwan
  {
    symbol: 'TSM',
    name: 'Taiwan Semiconductor Manufacturing',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — Japan
  {
    symbol: 'TM',
    name: 'Toyota Motor Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'SONY',
    name: 'Sony Group Corporation',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'HMC',
    name: 'Honda Motor Co.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'MUFG',
    name: 'Mitsubishi UFJ Financial Group',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'SNE',
    name: 'Nintendo Co.',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — South Korea
  {
    symbol: 'SSNLF',
    name: 'Samsung Electronics',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — Australia
  {
    symbol: 'BHP',
    name: 'BHP Group Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'RIO',
    name: 'Rio Tinto plc',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — China
  {
    symbol: 'BABA',
    name: 'Alibaba Group Holding',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'TCEHY',
    name: 'Tencent Holdings',
    exchange: 'OTC',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'BIDU',
    name: 'Baidu Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'JD',
    name: 'JD.com Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Asia-Pacific — Singapore / SE Asia
  {
    symbol: 'SE',
    name: 'Sea Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'GRAB',
    name: 'Grab Holdings',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Latin America
  {
    symbol: 'MELI',
    name: 'MercadoLibre Inc.',
    exchange: 'NASDAQ',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'NU',
    name: 'Nu Holdings',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'ITUB',
    name: 'Itaú Unibanco Holding',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // Canada
  {
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'CNQ',
    name: 'Canadian Natural Resources',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'RY',
    name: 'Royal Bank of Canada',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'TD',
    name: 'Toronto-Dominion Bank',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  // India
  {
    symbol: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'WIT',
    name: 'Wipro Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
  {
    symbol: 'HDB',
    name: 'HDFC Bank Limited',
    exchange: 'NYSE',
    tradable: true,
    assetClass: 'intl_equity',
  },
];
