import type { AssetEntry } from './price-cache.types';

/**
 * Curated list of ~230 actively-traded US equities used as a fallback when
 * ALPACA_API_KEY / ALPACA_API_SECRET are not set (local dev, CI without creds).
 * Mirrors the shape returned by Alpaca's GET /v2/assets endpoint.
 */
export const MOCK_ASSETS: AssetEntry[] = [
  // Technology — NASDAQ
  { symbol: 'AAPL',  name: 'Apple Inc.',                        exchange: 'NASDAQ', tradable: true },
  { symbol: 'MSFT',  name: 'Microsoft Corporation',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'NVDA',  name: 'NVIDIA Corporation',                exchange: 'NASDAQ', tradable: true },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'GOOG',  name: 'Alphabet Inc. Class C',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'META',  name: 'Meta Platforms Inc.',               exchange: 'NASDAQ', tradable: true },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',                   exchange: 'NASDAQ', tradable: true },
  { symbol: 'TSLA',  name: 'Tesla Inc.',                        exchange: 'NASDAQ', tradable: true },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',                     exchange: 'NASDAQ', tradable: true },
  { symbol: 'CSCO',  name: 'Cisco Systems Inc.',                exchange: 'NASDAQ', tradable: true },
  { symbol: 'INTC',  name: 'Intel Corporation',                 exchange: 'NASDAQ', tradable: true },
  { symbol: 'AMD',   name: 'Advanced Micro Devices Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'QCOM',  name: 'QUALCOMM Incorporated',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'TXN',   name: 'Texas Instruments Incorporated',    exchange: 'NASDAQ', tradable: true },
  { symbol: 'MU',    name: 'Micron Technology Inc.',            exchange: 'NASDAQ', tradable: true },
  { symbol: 'AMAT',  name: 'Applied Materials Inc.',            exchange: 'NASDAQ', tradable: true },
  { symbol: 'LRCX',  name: 'Lam Research Corporation',          exchange: 'NASDAQ', tradable: true },
  { symbol: 'KLAC',  name: 'KLA Corporation',                   exchange: 'NASDAQ', tradable: true },
  { symbol: 'SNPS',  name: 'Synopsys Inc.',                     exchange: 'NASDAQ', tradable: true },
  { symbol: 'CDNS',  name: 'Cadence Design Systems Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'ADBE',  name: 'Adobe Inc.',                        exchange: 'NASDAQ', tradable: true },
  { symbol: 'CRM',   name: 'Salesforce Inc.',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'NOW',   name: 'ServiceNow Inc.',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'INTU',  name: 'Intuit Inc.',                       exchange: 'NASDAQ', tradable: true },
  { symbol: 'PANW',  name: 'Palo Alto Networks Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'CRWD',  name: 'CrowdStrike Holdings Inc.',         exchange: 'NASDAQ', tradable: true },
  { symbol: 'FTNT',  name: 'Fortinet Inc.',                     exchange: 'NASDAQ', tradable: true },
  { symbol: 'PLTR',  name: 'Palantir Technologies Inc.',        exchange: 'NYSE',   tradable: true },
  { symbol: 'SNOW',  name: 'Snowflake Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'DDOG',  name: 'Datadog Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'TEAM',  name: 'Atlassian Corporation',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'ZM',    name: 'Zoom Video Communications Inc.',    exchange: 'NASDAQ', tradable: true },
  { symbol: 'DOCU',  name: 'DocuSign Inc.',                     exchange: 'NASDAQ', tradable: true },
  { symbol: 'OKTA',  name: 'Okta Inc.',                         exchange: 'NASDAQ', tradable: true },
  { symbol: 'NET',   name: 'Cloudflare Inc.',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'MNDY',  name: 'monday.com Ltd.',                   exchange: 'NASDAQ', tradable: true },
  { symbol: 'S',     name: 'SentinelOne Inc.',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'ORCL',  name: 'Oracle Corporation',                exchange: 'NYSE',   tradable: true },
  { symbol: 'IBM',   name: 'International Business Machines',   exchange: 'NYSE',   tradable: true },
  { symbol: 'ACN',   name: 'Accenture plc',                     exchange: 'NYSE',   tradable: true },
  { symbol: 'MSCI',  name: 'MSCI Inc.',                         exchange: 'NYSE',   tradable: true },

  // Consumer tech / platforms
  { symbol: 'UBER',  name: 'Uber Technologies Inc.',            exchange: 'NYSE',   tradable: true },
  { symbol: 'LYFT',  name: 'Lyft Inc.',                         exchange: 'NASDAQ', tradable: true },
  { symbol: 'ABNB',  name: 'Airbnb Inc.',                       exchange: 'NASDAQ', tradable: true },
  { symbol: 'DASH',  name: 'DoorDash Inc.',                     exchange: 'NYSE',   tradable: true },
  { symbol: 'COIN',  name: 'Coinbase Global Inc.',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'HOOD',  name: 'Robinhood Markets Inc.',            exchange: 'NASDAQ', tradable: true },
  { symbol: 'SOFI',  name: 'SoFi Technologies Inc.',            exchange: 'NASDAQ', tradable: true },
  { symbol: 'AFRM',  name: 'Affirm Holdings Inc.',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'UPST',  name: 'Upstart Holdings Inc.',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'SQ',    name: 'Block Inc.',                        exchange: 'NYSE',   tradable: true },
  { symbol: 'PYPL',  name: 'PayPal Holdings Inc.',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'SHOP',  name: 'Shopify Inc.',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'ETSY',  name: 'Etsy Inc.',                         exchange: 'NASDAQ', tradable: true },
  { symbol: 'EBAY',  name: 'eBay Inc.',                         exchange: 'NASDAQ', tradable: true },
  { symbol: 'SNAP',  name: 'Snap Inc.',                         exchange: 'NYSE',   tradable: true },
  { symbol: 'PINS',  name: 'Pinterest Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'RBLX',  name: 'Roblox Corporation',                exchange: 'NYSE',   tradable: true },
  { symbol: 'TTWO',  name: 'Take-Two Interactive Software',     exchange: 'NASDAQ', tradable: true },
  { symbol: 'EA',    name: 'Electronic Arts Inc.',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'MTCH',  name: 'Match Group Inc.',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'DKNG',  name: 'DraftKings Inc.',                   exchange: 'NASDAQ', tradable: true },

  // Healthcare
  { symbol: 'JNJ',   name: 'Johnson & Johnson',                 exchange: 'NYSE',   tradable: true },
  { symbol: 'UNH',   name: 'UnitedHealth Group Inc.',           exchange: 'NYSE',   tradable: true },
  { symbol: 'LLY',   name: 'Eli Lilly and Company',             exchange: 'NYSE',   tradable: true },
  { symbol: 'ABBV',  name: 'AbbVie Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'MRK',   name: 'Merck & Co. Inc.',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'BMY',   name: 'Bristol-Myers Squibb Company',      exchange: 'NYSE',   tradable: true },
  { symbol: 'AMGN',  name: 'Amgen Inc.',                        exchange: 'NASDAQ', tradable: true },
  { symbol: 'GILD',  name: 'Gilead Sciences Inc.',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'REGN',  name: 'Regeneron Pharmaceuticals Inc.',    exchange: 'NASDAQ', tradable: true },
  { symbol: 'BIIB',  name: 'Biogen Inc.',                       exchange: 'NASDAQ', tradable: true },
  { symbol: 'VRTX',  name: 'Vertex Pharmaceuticals Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'MRNA',  name: 'Moderna Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'BNTX',  name: 'BioNTech SE',                       exchange: 'NASDAQ', tradable: true },
  { symbol: 'PFE',   name: 'Pfizer Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'CVS',   name: 'CVS Health Corporation',            exchange: 'NYSE',   tradable: true },
  { symbol: 'CI',    name: 'The Cigna Group',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'HUM',   name: 'Humana Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'ELV',   name: 'Elevance Health Inc.',              exchange: 'NYSE',   tradable: true },
  { symbol: 'MCK',   name: 'McKesson Corporation',              exchange: 'NYSE',   tradable: true },
  { symbol: 'IDXX',  name: 'IDEXX Laboratories Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'ZTS',   name: 'Zoetis Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'ISRG',  name: 'Intuitive Surgical Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'TMO',   name: 'Thermo Fisher Scientific Inc.',     exchange: 'NYSE',   tradable: true },
  { symbol: 'DHR',   name: 'Danaher Corporation',               exchange: 'NYSE',   tradable: true },
  { symbol: 'SYK',   name: 'Stryker Corporation',               exchange: 'NYSE',   tradable: true },
  { symbol: 'BSX',   name: 'Boston Scientific Corporation',     exchange: 'NYSE',   tradable: true },
  { symbol: 'MDT',   name: 'Medtronic plc',                     exchange: 'NYSE',   tradable: true },
  { symbol: 'EW',    name: 'Edwards Lifesciences Corporation',  exchange: 'NYSE',   tradable: true },
  { symbol: 'BDX',   name: 'Becton Dickinson and Company',      exchange: 'NYSE',   tradable: true },
  { symbol: 'DXCM',  name: 'DexCom Inc.',                       exchange: 'NASDAQ', tradable: true },
  { symbol: 'ALGN',  name: 'Align Technology Inc.',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'IQV',   name: 'IQVIA Holdings Inc.',               exchange: 'NYSE',   tradable: true },

  // Financials
  { symbol: 'JPM',   name: 'JPMorgan Chase & Co.',              exchange: 'NYSE',   tradable: true },
  { symbol: 'BAC',   name: 'Bank of America Corporation',       exchange: 'NYSE',   tradable: true },
  { symbol: 'WFC',   name: 'Wells Fargo & Company',             exchange: 'NYSE',   tradable: true },
  { symbol: 'GS',    name: 'The Goldman Sachs Group Inc.',      exchange: 'NYSE',   tradable: true },
  { symbol: 'MS',    name: 'Morgan Stanley',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'BLK',   name: 'BlackRock Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'SCHW',  name: 'The Charles Schwab Corporation',    exchange: 'NYSE',   tradable: true },
  { symbol: 'V',     name: 'Visa Inc.',                         exchange: 'NYSE',   tradable: true },
  { symbol: 'MA',    name: 'Mastercard Incorporated',           exchange: 'NYSE',   tradable: true },
  { symbol: 'AXP',   name: 'American Express Company',          exchange: 'NYSE',   tradable: true },
  { symbol: 'COF',   name: 'Capital One Financial Corporation', exchange: 'NYSE',   tradable: true },
  { symbol: 'USB',   name: 'U.S. Bancorp',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'PNC',   name: 'The PNC Financial Services Group',  exchange: 'NYSE',   tradable: true },
  { symbol: 'TFC',   name: 'Truist Financial Corporation',      exchange: 'NYSE',   tradable: true },
  { symbol: 'C',     name: 'Citigroup Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'BK',    name: 'The Bank of New York Mellon',       exchange: 'NYSE',   tradable: true },
  { symbol: 'STT',   name: 'State Street Corporation',          exchange: 'NYSE',   tradable: true },
  { symbol: 'FITB',  name: 'Fifth Third Bancorp',               exchange: 'NASDAQ', tradable: true },
  { symbol: 'KEY',   name: 'KeyCorp',                           exchange: 'NYSE',   tradable: true },
  { symbol: 'RF',    name: 'Regions Financial Corporation',     exchange: 'NYSE',   tradable: true },
  { symbol: 'CFG',   name: 'Citizens Financial Group Inc.',     exchange: 'NYSE',   tradable: true },
  { symbol: 'ALLY',  name: 'Ally Financial Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'MSCI',  name: 'MSCI Inc.',                         exchange: 'NYSE',   tradable: true },

  // Energy
  { symbol: 'XOM',   name: 'Exxon Mobil Corporation',           exchange: 'NYSE',   tradable: true },
  { symbol: 'CVX',   name: 'Chevron Corporation',               exchange: 'NYSE',   tradable: true },
  { symbol: 'COP',   name: 'ConocoPhillips',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'SLB',   name: 'Schlumberger Limited',              exchange: 'NYSE',   tradable: true },
  { symbol: 'EOG',   name: 'EOG Resources Inc.',                exchange: 'NYSE',   tradable: true },
  { symbol: 'MPC',   name: 'Marathon Petroleum Corporation',    exchange: 'NYSE',   tradable: true },
  { symbol: 'PSX',   name: 'Phillips 66',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'VLO',   name: 'Valero Energy Corporation',         exchange: 'NYSE',   tradable: true },
  { symbol: 'OXY',   name: 'Occidental Petroleum Corporation',  exchange: 'NYSE',   tradable: true },
  { symbol: 'DVN',   name: 'Devon Energy Corporation',          exchange: 'NYSE',   tradable: true },
  { symbol: 'HES',   name: 'Hess Corporation',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'KMI',   name: 'Kinder Morgan Inc.',                exchange: 'NYSE',   tradable: true },
  { symbol: 'WMB',   name: 'Williams Companies Inc.',           exchange: 'NYSE',   tradable: true },
  { symbol: 'OKE',   name: 'ONEOK Inc.',                        exchange: 'NYSE',   tradable: true },
  { symbol: 'EPD',   name: 'Enterprise Products Partners L.P.', exchange: 'NYSE',   tradable: true },
  { symbol: 'ET',    name: 'Energy Transfer LP',                exchange: 'NYSE',   tradable: true },

  // Consumer Discretionary
  { symbol: 'HD',    name: 'The Home Depot Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'LOW',   name: 'Lowe\'s Companies Inc.',            exchange: 'NYSE',   tradable: true },
  { symbol: 'TGT',   name: 'Target Corporation',                exchange: 'NYSE',   tradable: true },
  { symbol: 'MCD',   name: 'McDonald\'s Corporation',           exchange: 'NYSE',   tradable: true },
  { symbol: 'SBUX',  name: 'Starbucks Corporation',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'NKE',   name: 'NIKE Inc.',                         exchange: 'NYSE',   tradable: true },
  { symbol: 'LULU',  name: 'lululemon athletica inc.',          exchange: 'NASDAQ', tradable: true },
  { symbol: 'ROST',  name: 'Ross Stores Inc.',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'TJX',   name: 'The TJX Companies Inc.',            exchange: 'NYSE',   tradable: true },
  { symbol: 'CMG',   name: 'Chipotle Mexican Grill Inc.',       exchange: 'NYSE',   tradable: true },
  { symbol: 'YUM',   name: 'Yum! Brands Inc.',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'QSR',   name: 'Restaurant Brands International',   exchange: 'NYSE',   tradable: true },
  { symbol: 'DRI',   name: 'Darden Restaurants Inc.',           exchange: 'NYSE',   tradable: true },
  { symbol: 'W',     name: 'Wayfair Inc.',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'BKNG',  name: 'Booking Holdings Inc.',             exchange: 'NASDAQ', tradable: true },
  { symbol: 'EXPE',  name: 'Expedia Group Inc.',                exchange: 'NASDAQ', tradable: true },
  { symbol: 'MAR',   name: 'Marriott International Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'HLT',   name: 'Hilton Worldwide Holdings Inc.',    exchange: 'NYSE',   tradable: true },
  { symbol: 'CCL',   name: 'Carnival Corporation',              exchange: 'NYSE',   tradable: true },
  { symbol: 'RCL',   name: 'Royal Caribbean Group',             exchange: 'NYSE',   tradable: true },
  { symbol: 'NCLH',  name: 'Norwegian Cruise Line Holdings',    exchange: 'NYSE',   tradable: true },
  { symbol: 'DAL',   name: 'Delta Air Lines Inc.',              exchange: 'NYSE',   tradable: true },
  { symbol: 'UAL',   name: 'United Airlines Holdings Inc.',     exchange: 'NASDAQ', tradable: true },
  { symbol: 'AAL',   name: 'American Airlines Group Inc.',      exchange: 'NASDAQ', tradable: true },
  { symbol: 'LUV',   name: 'Southwest Airlines Co.',            exchange: 'NYSE',   tradable: true },

  // Consumer Staples
  { symbol: 'WMT',   name: 'Walmart Inc.',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'COST',  name: 'Costco Wholesale Corporation',      exchange: 'NASDAQ', tradable: true },
  { symbol: 'KO',    name: 'The Coca-Cola Company',             exchange: 'NYSE',   tradable: true },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'PG',    name: 'The Procter & Gamble Company',      exchange: 'NYSE',   tradable: true },
  { symbol: 'CL',    name: 'Colgate-Palmolive Company',         exchange: 'NYSE',   tradable: true },
  { symbol: 'KMB',   name: 'Kimberly-Clark Corporation',        exchange: 'NYSE',   tradable: true },
  { symbol: 'MDLZ',  name: 'Mondelez International Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'GIS',   name: 'General Mills Inc.',                exchange: 'NYSE',   tradable: true },
  { symbol: 'K',     name: 'Kellanova',                         exchange: 'NYSE',   tradable: true },
  { symbol: 'HSY',   name: 'The Hershey Company',               exchange: 'NYSE',   tradable: true },
  { symbol: 'TSN',   name: 'Tyson Foods Inc.',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'KHC',   name: 'The Kraft Heinz Company',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'STZ',   name: 'Constellation Brands Inc.',         exchange: 'NYSE',   tradable: true },
  { symbol: 'MO',    name: 'Altria Group Inc.',                 exchange: 'NYSE',   tradable: true },
  { symbol: 'PM',    name: 'Philip Morris International Inc.',  exchange: 'NYSE',   tradable: true },

  // Industrials
  { symbol: 'BA',    name: 'The Boeing Company',                exchange: 'NYSE',   tradable: true },
  { symbol: 'CAT',   name: 'Caterpillar Inc.',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'HON',   name: 'Honeywell International Inc.',      exchange: 'NASDAQ', tradable: true },
  { symbol: 'MMM',   name: '3M Company',                        exchange: 'NYSE',   tradable: true },
  { symbol: 'GE',    name: 'GE Aerospace',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'UPS',   name: 'United Parcel Service Inc.',        exchange: 'NYSE',   tradable: true },
  { symbol: 'FDX',   name: 'FedEx Corporation',                 exchange: 'NYSE',   tradable: true },
  { symbol: 'LMT',   name: 'Lockheed Martin Corporation',       exchange: 'NYSE',   tradable: true },
  { symbol: 'RTX',   name: 'RTX Corporation',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'NOC',   name: 'Northrop Grumman Corporation',      exchange: 'NYSE',   tradable: true },
  { symbol: 'GD',    name: 'General Dynamics Corporation',      exchange: 'NYSE',   tradable: true },
  { symbol: 'DE',    name: 'Deere & Company',                   exchange: 'NYSE',   tradable: true },
  { symbol: 'EMR',   name: 'Emerson Electric Co.',              exchange: 'NYSE',   tradable: true },
  { symbol: 'ETN',   name: 'Eaton Corporation plc',             exchange: 'NYSE',   tradable: true },
  { symbol: 'PH',    name: 'Parker-Hannifin Corporation',       exchange: 'NYSE',   tradable: true },
  { symbol: 'ROK',   name: 'Rockwell Automation Inc.',          exchange: 'NYSE',   tradable: true },
  { symbol: 'ROP',   name: 'Roper Technologies Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'AME',   name: 'AMETEK Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'TDG',   name: 'TransDigm Group Incorporated',      exchange: 'NYSE',   tradable: true },
  { symbol: 'IR',    name: 'Ingersoll Rand Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'ODFL',  name: 'Old Dominion Freight Line Inc.',    exchange: 'NASDAQ', tradable: true },
  { symbol: 'JBHT',  name: 'J.B. Hunt Transport Services',      exchange: 'NASDAQ', tradable: true },
  { symbol: 'XPO',   name: 'XPO Inc.',                          exchange: 'NYSE',   tradable: true },
  { symbol: 'CARR',  name: 'Carrier Global Corporation',        exchange: 'NYSE',   tradable: true },
  { symbol: 'OTIS',  name: 'Otis Worldwide Corporation',        exchange: 'NYSE',   tradable: true },

  // Communication Services
  { symbol: 'NFLX',  name: 'Netflix Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'DIS',   name: 'The Walt Disney Company',           exchange: 'NYSE',   tradable: true },
  { symbol: 'CMCSA', name: 'Comcast Corporation',               exchange: 'NASDAQ', tradable: true },
  { symbol: 'VZ',    name: 'Verizon Communications Inc.',       exchange: 'NYSE',   tradable: true },
  { symbol: 'T',     name: 'AT&T Inc.',                         exchange: 'NYSE',   tradable: true },
  { symbol: 'TMUS',  name: 'T-Mobile US Inc.',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'CHTR',  name: 'Charter Communications Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'PARA',  name: 'Paramount Global',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'WBD',   name: 'Warner Bros. Discovery Inc.',       exchange: 'NASDAQ', tradable: true },
  { symbol: 'FOXA',  name: 'Fox Corporation Class A',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'SIRI',  name: 'Sirius XM Holdings Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'SPOT',  name: 'Spotify Technology S.A.',           exchange: 'NYSE',   tradable: true },

  // Utilities
  { symbol: 'NEE',   name: 'NextEra Energy Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'DUK',   name: 'Duke Energy Corporation',           exchange: 'NYSE',   tradable: true },
  { symbol: 'SO',    name: 'Southern Company',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'AEP',   name: 'American Electric Power Company',   exchange: 'NASDAQ', tradable: true },
  { symbol: 'D',     name: 'Dominion Energy Inc.',              exchange: 'NYSE',   tradable: true },
  { symbol: 'EXC',   name: 'Exelon Corporation',                exchange: 'NASDAQ', tradable: true },
  { symbol: 'XEL',   name: 'Xcel Energy Inc.',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'SRE',   name: 'Sempra',                            exchange: 'NYSE',   tradable: true },
  { symbol: 'PCG',   name: 'PG&E Corporation',                  exchange: 'NYSE',   tradable: true },
  { symbol: 'AWK',   name: 'American Water Works Company',      exchange: 'NYSE',   tradable: true },
  { symbol: 'CEG',   name: 'Constellation Energy Corporation',  exchange: 'NASDAQ', tradable: true },
  { symbol: 'VST',   name: 'Vistra Corp.',                      exchange: 'NYSE',   tradable: true },

  // Real Estate
  { symbol: 'AMT',   name: 'American Tower Corporation',        exchange: 'NYSE',   tradable: true },
  { symbol: 'PLD',   name: 'Prologis Inc.',                     exchange: 'NYSE',   tradable: true },
  { symbol: 'CCI',   name: 'Crown Castle Inc.',                 exchange: 'NYSE',   tradable: true },
  { symbol: 'EQIX',  name: 'Equinix Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'O',     name: 'Realty Income Corporation',         exchange: 'NYSE',   tradable: true },
  { symbol: 'SPG',   name: 'Simon Property Group Inc.',         exchange: 'NYSE',   tradable: true },
  { symbol: 'WELL',  name: 'Welltower Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'AVB',   name: 'AvalonBay Communities Inc.',        exchange: 'NYSE',   tradable: true },
  { symbol: 'EQR',   name: 'Equity Residential',                exchange: 'NYSE',   tradable: true },
  { symbol: 'PSA',   name: 'Public Storage',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'VTR',   name: 'Ventas Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'ARE',   name: 'Alexandria Real Estate Equities',   exchange: 'NYSE',   tradable: true },
  { symbol: 'MAA',   name: 'Mid-America Apartment Communities', exchange: 'NYSE',   tradable: true },

  // Materials
  { symbol: 'LIN',   name: 'Linde plc',                         exchange: 'NASDAQ', tradable: true },
  { symbol: 'SHW',   name: 'The Sherwin-Williams Company',      exchange: 'NYSE',   tradable: true },
  { symbol: 'FCX',   name: 'Freeport-McMoRan Inc.',             exchange: 'NYSE',   tradable: true },
  { symbol: 'NEM',   name: 'Newmont Corporation',               exchange: 'NYSE',   tradable: true },
  { symbol: 'APD',   name: 'Air Products and Chemicals Inc.',   exchange: 'NYSE',   tradable: true },
  { symbol: 'ECL',   name: 'Ecolab Inc.',                       exchange: 'NYSE',   tradable: true },
  { symbol: 'DD',    name: 'DuPont de Nemours Inc.',            exchange: 'NYSE',   tradable: true },
  { symbol: 'PPG',   name: 'PPG Industries Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'NUE',   name: 'Nucor Corporation',                 exchange: 'NYSE',   tradable: true },
  { symbol: 'VMC',   name: 'Vulcan Materials Company',          exchange: 'NYSE',   tradable: true },
  { symbol: 'MLM',   name: 'Martin Marietta Materials Inc.',    exchange: 'NYSE',   tradable: true },
  { symbol: 'ALB',   name: 'Albemarle Corporation',             exchange: 'NYSE',   tradable: true },
  { symbol: 'CF',    name: 'CF Industries Holdings Inc.',       exchange: 'NYSE',   tradable: true },
  { symbol: 'MOS',   name: 'The Mosaic Company',                exchange: 'NYSE',   tradable: true },

  // Automotive / EVs
  { symbol: 'F',     name: 'Ford Motor Company',                exchange: 'NYSE',   tradable: true },
  { symbol: 'GM',    name: 'General Motors Company',            exchange: 'NYSE',   tradable: true },
  { symbol: 'RIVN',  name: 'Rivian Automotive Inc.',            exchange: 'NASDAQ', tradable: true },
  { symbol: 'LCID',  name: 'Lucid Group Inc.',                  exchange: 'NASDAQ', tradable: true },
  { symbol: 'NIO',   name: 'NIO Inc.',                          exchange: 'NYSE',   tradable: true },
  { symbol: 'XPEV',  name: 'XPeng Inc.',                        exchange: 'NYSE',   tradable: true },
  { symbol: 'LI',    name: 'Li Auto Inc.',                      exchange: 'NASDAQ', tradable: true },

  // Semiconductors (additional)
  { symbol: 'TSM',   name: 'Taiwan Semiconductor Manufacturing', exchange: 'NYSE',  tradable: true },
  { symbol: 'ASML',  name: 'ASML Holding N.V.',                 exchange: 'NASDAQ', tradable: true },
  { symbol: 'MRVL',  name: 'Marvell Technology Inc.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'NXPI',  name: 'NXP Semiconductors N.V.',           exchange: 'NASDAQ', tradable: true },
  { symbol: 'ON',    name: 'ON Semiconductor Corporation',      exchange: 'NASDAQ', tradable: true },
  { symbol: 'STM',   name: 'STMicroelectronics N.V.',           exchange: 'NYSE',   tradable: true },
  { symbol: 'WOLF',  name: 'Wolfspeed Inc.',                    exchange: 'NYSE',   tradable: true },
  { symbol: 'SMCI',  name: 'Super Micro Computer Inc.',         exchange: 'NASDAQ', tradable: true },
  { symbol: 'ARM',   name: 'Arm Holdings plc',                  exchange: 'NASDAQ', tradable: true },

  // Cloud / SaaS (additional)
  { symbol: 'ZS',    name: 'Zscaler Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'WDAY',  name: 'Workday Inc.',                      exchange: 'NASDAQ', tradable: true },
  { symbol: 'TTD',   name: 'The Trade Desk Inc.',               exchange: 'NASDAQ', tradable: true },
  { symbol: 'APP',   name: 'AppLovin Corporation',              exchange: 'NASDAQ', tradable: true },
  { symbol: 'HUBS',  name: 'HubSpot Inc.',                      exchange: 'NYSE',   tradable: true },
  { symbol: 'BILL',  name: 'BILL Holdings Inc.',                exchange: 'NYSE',   tradable: true },
  { symbol: 'ZI',    name: 'ZoomInfo Technologies Inc.',        exchange: 'NASDAQ', tradable: true },
  { symbol: 'U',     name: 'Unity Software Inc.',               exchange: 'NYSE',   tradable: true },
  { symbol: 'GTLB',  name: 'GitLab Inc.',                       exchange: 'NASDAQ', tradable: true },
];
